#pragma once

#define STEAMROLL_DEFAULT_THREADS			4
#define STEAMROLL_DEFAULT_FILE				_T("")
#define STEAMROLL_DEFAULT_OUTPUT			_T("")
#define STEAMROLL_DEFAULT_USER				_T("")
#define STEAMROLL_DEFAULT_VERBOSE			TRUE
#define STEAMROLL_DEFAULT_DISABLEDUSERS		FALSE
#define STEAMROLL_DEFAULT_EXPIREDPASSWORDS	FALSE
#define STEAMROLL_DEFAULT_LOCKOUTS			FALSE
#define STEAMROLL_DEFAULT_AVCHECK			FALSE

typedef struct _STEAMROLL_OPTIONS
{
	TCHAR	szFile[MAX_PATH];
	TCHAR	szUser[MAX_PATH];
	TCHAR	szOutput[MAX_PATH];
	BYTE	nThreads;
	BOOL	bVerbose;
	BOOL	bDisabledUsers;
	BOOL	bExpiredPasswords;
	BOOL	bLockouts;
	BOOL	bAVCheck;
} STEAMROLL_OPTIONS, *PSTEAMROLL_OPTIONS;